#
# Jenkins pipeline for CNaaS
#

disabled: false

git:
  extensions:
    shallow_clone: true

extra_jobs:
  - name: cnaas-nac-front
    builders:
      - docker
    docker_name: cnaas/nac-front
    docker_context_dir: docker/front
