#
# Jenkins pipeline for CNaaS
#

disabled: false

git:
  branch: develop
  extensions:
    shallow_clone: true

extra_jobs:
  - name: cnaas-nac-front
    git:
      brach: develop
    builders:
      - docker
    docker_name: cnaas/nac-front
    docker_context_dir: docker/front

  - name: cnaas-nac-front
    git:
      branch: master
    builders:
      - docker
    docker_name: cnaas/nac-front
    docker_context_dir: docker/front
    docker_tags:
      - "v0.1.0"
