#
# Jenkins pipeline for CNaaS
#

disabled: false

extra_jobs:
  - name: cnaas-nac-front
    git:
      brach: develop
    builders:
      - docker
    docker_name: cnaas/nac-front
    docker_context_dir: docker/front
