version: '3.7'
services:
  cnaas_front:
    build: ./front/
    ports:
      - 4443:4443
    environment:
      - NAC_API_URL=
      - AUTH_API_URL=
    volumes:
      - type: volume
        source: cnaas-front-cert
        target: /opt/cnaas/cert
volumes:
  cnaas-front-cert:
    external: true

