version: '3.7'
services:
  cnaas_front:
    build: ./front/
    ports:
      - 4443:4443
    environment:
      - NAC_API_URL=https://su-nac1.cnaas.io:1443
      - NAC_FRONT_URL=https://su-nac1.cnaas.io
      - AUTH_API_URL=https://su-auth.cnaas.io
    volumes:
      - type: volume
        source: cnaas-front-cert
        target: /opt/cnaas/cert
volumes:
  cnaas-front-cert:
    external: true

