server {
    listen 4443 ssl;
    server_name cnaas-nac-front;
    client_max_body_size 200M;

    ssl on;
    ssl_certificate /opt/cnaas/certs/cnaasfront_combined.crt;
    ssl_certificate_key /opt/cnaas/certs/cnaasfront.key;
    
    location /api {
        proxy_pass https://nac_api:1443;
    }

    location / {
        root /opt/cnaas/static;
        include /etc/nginx/mime.types;
        try_files $uri $uri/ /index.html;
    }
}
